import type { NextPage } from "next";
import Head from "next/head";
import { Modal, Feeds } from "../components";
import { useState } from "react";
const Home: NextPage = () => {
  const [modalOpen, setModalOpen] = useState<Boolean>(false);

  return (
    <div>
      <Head>
        <title>PUSH APP</title>
        <meta
          name="descri
        ption"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Modal isOpen={modalOpen} contents="tetet" modalOpen={setModalOpen} />
        <Feeds modalOpen={setModalOpen} />
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
