import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>PUSH APP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        앞으로 여기다가 계속 올릴거에요.
        푸시앱 떡상 가즈아!!
      </main>

      <footer >
       
      </footer>
    </div>
  )
}

export default Home
